version: '3'
services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres_db'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=Postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

  elasticsearch:
    image: 'elasticsearch:6.5.0'
    container_name: 'elasticsearch'
    environment:
        - 'discovery.type=single-node'
        - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ports:
        - '9200:9200'
    volumes:
        - 'elasticsearch_data:/usr/share/elasticsearch/data'

volumes:
  postgres_data:
  elasticsearch_data: